/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tablasfinanzas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 *
 * @author BRAYAN
 */
public class menuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuprincipal
     */
    public menuprincipal() {

        initComponents();
         ImageIcon imgIcon = new ImageIcon(getClass().getResource("/images/menu1.png"));
        Image imgEscalada = imgIcon.getImage().getScaledInstance(jLabel3.getWidth(),
                jLabel3.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado = new ImageIcon(imgEscalada);
        jLabel3.setIcon(iconoEscalado);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/icf.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        btnSiguiente = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        RdFlujos = new javax.swing.JRadioButton();
        RdAmortizacionesG = new javax.swing.JRadioButton();
        RdAmortizaciones = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSiguiente.setBackground(new java.awt.Color(51, 51, 76));
        btnSiguiente.setForeground(new java.awt.Color(248, 248, 248));
        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setBorderPainted(false);
        btnSiguiente.setFocusPainted(false);
        btnSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSiguiente.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btnSiguiente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton2.png"))); // NOI18N
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 90, 32));

        btnCancelar.setForeground(new java.awt.Color(248, 248, 248));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btnCancelar.setText("Cerrar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setDisabledIcon(null);
        btnCancelar.setDisabledSelectedIcon(null);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton1.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton2.png"))); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 83, 32));

        RdFlujos.setBackground(new java.awt.Color(51, 51, 76));
        grupo1.add(RdFlujos);
        RdFlujos.setForeground(new java.awt.Color(248, 248, 248));
        RdFlujos.setText("Flujos");
        RdFlujos.setFocusPainted(false);
        RdFlujos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdFlujosActionPerformed(evt);
            }
        });
        getContentPane().add(RdFlujos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        RdAmortizacionesG.setBackground(new java.awt.Color(51, 51, 76));
        grupo1.add(RdAmortizacionesG);
        RdAmortizacionesG.setForeground(new java.awt.Color(248, 248, 248));
        RdAmortizacionesG.setText("Amortizaciones con periodo de gracia");
        RdAmortizacionesG.setFocusPainted(false);
        getContentPane().add(RdAmortizacionesG, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        RdAmortizaciones.setBackground(new java.awt.Color(51, 51, 76));
        grupo1.add(RdAmortizaciones);
        RdAmortizaciones.setForeground(new java.awt.Color(248, 248, 248));
        RdAmortizaciones.setText("Amortizaciones");
        RdAmortizaciones.setFocusPainted(false);
        RdAmortizaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdAmortizacionesActionPerformed(evt);
            }
        });
        getContentPane().add(RdAmortizaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 248, 248));
        jLabel1.setText("Escoga una opcion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        jLabel2.setFont(new java.awt.Font("Eras Bold ITC", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 248, 248));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 20, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu1.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 211));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed

        if (RdAmortizaciones.isSelected()==true){
            Tabla tabla =new Tabla();
            tabla.setVisible(true);
            this.dispose();
        }
        if (RdAmortizacionesG.isSelected()==true){
            TablaG tablaG =new TablaG();
            tablaG.setVisible(true);
            this.dispose();
        }
        if (RdFlujos.isSelected()==true){
            tablaFlujos flujos =new tablaFlujos();
            flujos.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void RdAmortizacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdAmortizacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdAmortizacionesActionPerformed

    private void RdFlujosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdFlujosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdFlujosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           
             for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
           
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RdAmortizaciones;
    private javax.swing.JRadioButton RdAmortizacionesG;
    private javax.swing.JRadioButton RdFlujos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
